application: rebboj
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: public/stylesheets

- url: /javascript
  static_dir: public/javascript

- url: /(review)?
  script: controllers/index_controller.py

- url: /companies.*
  script: controllers/company_controller.py